<a href="https://colab.research.google.com/github/guptamadhav11/AI-LAB/blob/main/BasicsPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
myList=[1, "mmm" ,3 ,4]
myList

[1, 'mmm', 3, 4]

In [ ]:
myList[0:3]


[1, 'mmm', 3]

In [ ]:
myList[1:5]

['mmm', 3, 4]

In [ ]:
5 in myList

False

In [ ]:
len(myList)

4

In [ ]:
name='Madhav'
last='Gupta'
name+' '+last


'Madhav Gupta'

In [ ]:
for i in range(1,10,2):
  print(i)

1
3
5
7
9


In [ ]:
def relu(x):
  if(x>=0):
    return x
  else:
    return 0


print(relu(-5))


0


In [5]:
def EuclidianNorm(vector):
  sum=0
  for i in vector:
    sum=sum+i**2
  norm=sum**(1/2)
  return norm
import numpy as np
vector=[0.5, -1.2, 3.3, 4.5]
print(EuclidianNorm(vector))

5.729746940310715


In [2]:
 def max(List):
   max=List[0]
   for i in range(len(List)-1):
    if(List[i+1]>max):
      max=List[i+1]

   return max
v=[0.5, 985, 3.3, 1.2,125,54]
print(max(v))

985


In [13]:


def bubblesort(List):
  for j in range(1,len(List)):
   for i in range(len(List)-j):
    if(List[i]>List[i+1]):
      c=List[i]
      List[i]=List[i+1]
      List[i+1]=c
      ##swap( id(List[i]),id(List[i+1]))

List=[9,8,7,-6,5,4,3,2,1]
bubblesort(List)
print(List)

[-6, 1, 2, 3, 4, 5, 7, 8, 9]


In [48]:
import numpy as np
my_array=np.array([1,2,3,4,17])
my_array

array([ 1,  2,  3,  4, 17])

In [25]:
my_2Darray=np.array([[1,2,3,4],[5,6,7,8]])
my_2Darray

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
my_2Darray[:,2]

array([3, 7])

In [43]:
print(my_array.shape)

(5,)


In [44]:
my_2Darray.dtype

dtype('int64')

In [40]:
print(my_2Darray.shape)

(2, 4)


In [50]:
zeroarray=np.zeros((2,3))

In [57]:
tupple=(1,2,3,4,'Madhav')

print(tupple[3])
print(type(tupple))
print(type(1))


4
<class 'tuple'>
<class 'int'>


In [29]:
a=[[1,2,3],"madhav",[4,5,6],"raghav",[8],[9,10]]

#for i in a:
  #print(i)
  #for j in i:
   #       print(j)


In [1]:
di={

      "madhav":[1,2,3,4],
      2:"badgg",
      3:[5,6,7],
      4:"d",
      5:"e",
      6:"f"
}
for i in di:
   print(di[i])
   for j in di[i]:
     print(j)






[1, 2, 3, 4]
1
2
3
4
badgg
b
a
d
g
g
[5, 6, 7]
5
6
7
d
d
e
e
f
f


In [2]:
l=[1,2,3,4]
l2=[1,2,3,4]
l.extend(l2)
l

[1, 2, 3, 4, 1, 2, 3, 4]

In [56]:
l=[ {

     1:"a",
     4:"baaa",
     "c":3
},2,3,4,"madhav"]
print(l[0][4][3])

a
