<a href="https://colab.research.google.com/github/guptamadhav11/mmggg/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

In [ ]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
b=np.array([1,2,3,4,5])
print
b.ndim

1

In [ ]:
a.dtype
b.dtype

dtype('int64')

In [ ]:
a.shape

(2, 6)

In [ ]:
b.shape

(5,)

In [ ]:
b.size

5

In [ ]:
a.size

12

In [ ]:
a.ndim

2

In [ ]:
b.ndim

1

In [ ]:
b.itemsize

8

In [ ]:
a.itemsize

8

In [ ]:
b.size * b.itemsize
b.nbytes

40

In [ ]:
a.size * a.itemsize
a.nbytes

96

In [ ]:
a[1,:]

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
b[4]

5

In [ ]:
# 3-D array

A=np.array([ [[1,2],[3,4]]  , [[5,6],[7,8]]  , [[9,10],[11,12]]  ])
print(A)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
z=np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [ ]:
z1=np.zeros([2,3])
z1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
o=np.ones([3,4])
print(o)
print(o.dtype)
print(o.itemsize)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
8


In [ ]:
l=[ (1,2,3),(3,8,9),(4,5,6)]
x=np.array(l)
print(x)

[[1 2 3]
 [3 8 9]
 [4 5 6]]


In [ ]:
any=np.full([3,4],77)
print(any)

[[77 77 77 77]
 [77 77 77 77]
 [77 77 77 77]]


In [ ]:
np.random.rand(3,3)

array([[0.82871335, 0.52725127, 0.42658251],
       [0.79887173, 0.83342495, 0.27489772],
       [0.09866734, 0.02405958, 0.64027036]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
free=np.ones([5,5],dtype='int32')
print(free)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
z=np.zeros([3,3],dtype='int32')
print(z)
z[1,1]=9


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
free[1:4,1:4]=z
print(free)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
p=np.array([1,2,3,4,5])
q=p
q[0]=100
print(p)
print(q)



[100   2   3   4   5]
[100   2   3   4   5]


In [ ]:
p=np.array([1,2,3,4,5])
q=p.copy()
q[0]=100
print(p)
print(q)

[1 2 3 4 5]
[100   2   3   4   5]


NumPy in Mathematics

In [ ]:
t=np.array([1,2,3,4,5,6])
r=np.array([1,1,2,2,3,7])
print(t*r)
print(t+2)

[ 1  2  6  8 15 42]
[3 4 5 6 7 8]


In [25]:
t=np.array([[1,2],[3,4],[5,6]])
h=np.array([[2,3],[3,4],[5,6]])
t+h

array([[ 3,  5],
       [ 6,  8],
       [10, 12]])

In [ ]:
print(t-2)

[-1  0  1  2  3]


In [ ]:
print(t*2)

[ 2  4  6  8 10]


In [ ]:
print(t**2)

[ 1  4  9 16 25]


In [ ]:
print(t/2)

[0.5 1.  1.5 2.  2.5]


Linear Algebra

In [ ]:
c=np.ones([3,2])
d=np.array([ [1,2],[3,4] ])
np.matmul(c,d)

array([[4., 6.],
       [4., 6.],
       [4., 6.]])

In [ ]:
e=np.identity(3)
np.linalg.det(e)

1.0

Statistics

In [ ]:
stats=np.array([ [1,2,9] , [4,5,6] ])
print(stats)
print(np.min(stats))


[[1 2 9]
 [4 5 6]]
1


In [ ]:
np.min(stats,axis=1)    # row wise minimum

array([1, 4])

In [ ]:
np.min(stats,axis=0)   #column wise minimum

array([1, 2, 6])

In [ ]:
np.sum(stats)

27

In [ ]:
np.sum(stats,axis=0)

array([ 5,  7, 15])

In [ ]:
np.sum(stats,axis=1)

array([12, 15])

Reorganising Arrays

In [ ]:
s=np.array([ [1,2,3],[4,5,6] ])
t=np.array([ [0,0,0],[0,0,0],[1,1,1] ])
np.vstack([s,t])

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [ ]:
u=np.array([ [1,2,3],[4,5,6] ])
v=np.array([ [0,0],[0,0] ])
np.hstack([u,v])

array([[1, 2, 3, 0, 0],
       [4, 5, 6, 0, 0]])

In [ ]:
t=np.array([1,2,3,4])
print(t)
s=np.array([6,7,8,9])
np.vstack([t,s])

[1 2 3 4]


array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [ ]:
l=[ [1,2] ,[3,4] ]
print(l)

[[1, 2], [3, 4]]


In [28]:
B=np.array([ [ [1,2],[3,4] ] ,[ [5,6 ],[7,8 ] ]  ])
print(B)
B[:,1,:]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[3, 4],
       [7, 8]])

In [34]:
def relu_numpy(x):
  max=np.max(x)
  x[[0,1],:]
  return max


x=relu_numpy(np.array([ [10,20,30] ,[5,6,7] ]))
print(x)

30
